name: Release (GitHub/PyPI)

on:
  workflow_dispatch:
  push:
    tags:
      - '*'  # Trigger on all tags initially, but tag and release privilege are verified in _build-wheel-release-upload.yml

jobs:
  release:
    permissions:
      contents: write
    uses: bobleesj/release-scripts/.github/workflows/_build-wheel-release-upload.yml@v0
    with:
      project: diffpy.pdffit2
      c_extension: true

    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
