name: CI

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:
  pull_request:

jobs:
  coverage:
    uses: bobleesj/release-scripts/.github/workflows/_matrix-and-codecov-on-merge-to-main.yml@matrix
    with:
      project: diffpy.pdffit2
      c_extension: true
      headless: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
