name: Matrix test

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Python ${{ matrix.python-version }}, OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            # python-version: ['3.10', '3.11', '3.12']
            python-version: ['3.12']
            os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - name: check out diffpy.pdffit2
        uses: actions/checkout@v4

      - name: Initialize miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          auto-update-conda: true
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Conda config
        run: >-
          conda config --set always_yes yes
          --set changeps1 no

      - name: Install diffpy.pdffit2 and requirements
        run: |
          conda install --file requirements/run.txt
          conda install --file requirements/test.txt
          conda install --file requirements/build.txt
          python -m pip install -r requirements/pip.txt
          python -m pip install . --no-deps

      - name: Validate diffpy.pdffit2
        run: |
          pytest tests/test_init.py
          pip list
