name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]

    steps:
      - name: Check out diffpy.pdffit2
        uses: actions/checkout@v4

      - name: Initialize miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install runtime requirements
        run: |
          conda install --file requirements/run.txt
          conda install --file requirements/test.txt
          conda install --file requirements/build.txt
          python -m pip install -r requirements/pip.txt
          python -m pip install . --no-deps

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.1
        # You can set environment variables or other options here if needed

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
